-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2019-01-31 14:31:05.98

-- tables
-- Table: DEPARTAMENTO
-- DROP DATABASE iVentas;
CREATE DATABASE iVentas CHAR SET utf8;
USE iVentas;
CREATE TABLE DEPARTAMENTO (
    CODDEP int NOT NULL COMMENT 'Código del Departamento',
    NOMDEP varchar(50) NOT NULL COMMENT 'Nombre del Departamento',
    CONSTRAINT DEPARTAMENTO_pk PRIMARY KEY (CODDEP)
);

-- Table: DISTRITO
CREATE TABLE DISTRITO (
    CODDIS int NOT NULL COMMENT 'Código del Distrito',
    NOMDIS varchar(50) NOT NULL COMMENT 'Nombre del Distrito',
    PROVINCIA_CODPROV int NOT NULL COMMENT 'Código de la Provincia al que pertenece el Distrito',
    CONSTRAINT DISTRITO_pk PRIMARY KEY (CODDIS)
);

-- Table: ENTRADASALIDA
CREATE TABLE ENTRADASALIDA (
    CODENSA int NOT NULL,
    PRODUCTO_CODPRO int NOT NULL,
    CNTEN int NOT NULL,
    FECEN date NOT NULL,
    CNTSA int NOT NULL,
    FECSA date NOT NULL,
    STOCK int NOT NULL,
    CONSTRAINT ENTRADASALIDA_pk PRIMARY KEY (CODENSA)
);

-- Table: MARCA
CREATE TABLE MARCA (
    CODMAR int NOT NULL AUTO_INCREMENT COMMENT 'Código de la Marca',
    NOMMAR varchar(50) NOT NULL COMMENT 'Nombre de la Marca',
    CONSTRAINT MARCA_pk PRIMARY KEY (CODMAR)
);

-- Table: MODELO
CREATE TABLE MODELO (
    CODMOD int NOT NULL AUTO_INCREMENT COMMENT 'Código del Modelo',
    NOMMOD varchar(100) NOT NULL COMMENT 'Nombre del Modelo',
    MARCA_CODMAR_MARMOD int NOT NULL COMMENT 'Código de la Marca a la que Pertenece el Modelo',
    CONSTRAINT MODELO_pk PRIMARY KEY (CODMOD)
);

-- Table: PERSONA
CREATE TABLE PERSONA (
    CODPER int NOT NULL AUTO_INCREMENT COMMENT 'Código de la Persona',
    NOMPER varchar(100) NOT NULL COMMENT 'Nombre de la Persona',
    APEPER varchar(100) NULL COMMENT 'Apellido de la Persona',
    DOCPER char(11) NOT NULL COMMENT 'Número de DNI de la persona',
    TLFPER char(12) NULL COMMENT 'Número de teléfono o celular de la Persona',
    TIPPER char(1) NOT NULL COMMENT 'Tipo de Persona:
A - admin
I - inventariador
V - vendedor
E - empresa
C - cliente',
    DISTRITO_CODDIS_DISPER int NOT NULL COMMENT 'Código del Distrito al que pertenece la Persona',
    DIRPER varchar(50) NOT NULL COMMENT 'Dirección de la Persona',
    USRLOGPER varchar(30) NULL,
    PSWLOGPER varchar(10) NULL,
    ESTLOGPER char(1) NULL,
    CONSTRAINT PERSONA_pk PRIMARY KEY (CODPER)
);

-- Table: PRODUCTO
CREATE TABLE PRODUCTO (
    CODPRO int NOT NULL AUTO_INCREMENT COMMENT 'Código del Producto',
    NOMPRO char(50) NOT NULL COMMENT 'Nombre del Producto',
    MODELO_CODMOD_MODPRO int NOT NULL COMMENT 'Código del Modelo al que pertenece el Producto',
    SERPRO varchar(100) NOT NULL COMMENT 'Número de Serie del Producto',
    PREPRO double(8,2) NOT NULL COMMENT 'Precio del Producto',
    URLIMGPRO varchar(300) NULL COMMENT 'URL de la imagen referencial del Producto',
    ATRIBPRO varchar(300) NOT NULL COMMENT 'Caracteristicas del Producto, en JSON:
Procesador, pantalla, resolucion, ram, etc',
    ESTPRO char(1) NOT NULL COMMENT 'Estado del Producto:
A - Activo
S - Suspendido
I - Inactivo',
    FECGARPRO varchar(10) NOT NULL COMMENT 'Fecha de Garantía del Producto',
    PERSONA_CODPER_PROVPRO int NOT NULL,
    CONSTRAINT PRODUCTO_pk PRIMARY KEY (CODPRO)
);

-- Table: PROVINCIA
CREATE TABLE PROVINCIA (
    CODPROV int NOT NULL COMMENT 'Código de la Provincia',
    NOMPROV varchar(50) NOT NULL COMMENT 'Nombre de la Provincia',
    DEPARTAMENTO_CODDEP int NOT NULL COMMENT 'Código del Departamento al que pertenece la Provincia',
    CONSTRAINT PROVINCIA_pk PRIMARY KEY (CODPROV)
);

-- Table: VENTA
CREATE TABLE VENTA (
    CODVEN int NOT NULL AUTO_INCREMENT COMMENT 'Código de la Venta',
    CODPER_VENVEN int NOT NULL COMMENT 'Código de la Persona que vendió el Producto',
    FECVEN date NOT NULL COMMENT 'Fecha en la que se hizo la Venta',
    HOVEN time NOT NULL COMMENT 'Hora de la Venta',
    TIPVEN char(1) NOT NULL COMMENT 'Tipo de Venta
B - Boleta
F - Factura
E - Electrónica
C - Crédito',
    CODPER_COMVEN int NOT NULL COMMENT 'Código de la Persona que compró el Producto',
    CONSTRAINT VENTA_pk PRIMARY KEY (CODVEN)
);

-- Table: VENTA_DETALLE
CREATE TABLE VENTA_DETALLE (
    CODDETVEN int NOT NULL AUTO_INCREMENT COMMENT 'Código del Detalle de la Venta',
    VENTA_CODVEN_VENVEN int NOT NULL COMMENT 'Código de la Venta',
    PRODUCTO_CODPRO_PROVEN int NOT NULL COMMENT 'Código del Producto que se vendió',
    CANTPROVEN int NOT NULL COMMENT 'Cantidad del Producto vendido',
    DSCPROVEN double(2,2) NOT NULL COMMENT 'Descuento del Producto',
    ESTVEN char(1) NOT NULL COMMENT 'Estado de la Venta:
G - Garantía
N - Normal
S - Suspendido',
    CONSTRAINT VENTA_DETALLE_pk PRIMARY KEY (CODDETVEN)
);

-- foreign keys
-- Reference: DETALLE_VENTA_PRODUCTO (table: VENTA_DETALLE)
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT DETALLE_VENTA_PRODUCTO FOREIGN KEY DETALLE_VENTA_PRODUCTO (PRODUCTO_CODPRO_PROVEN)
    REFERENCES PRODUCTO (CODPRO);

-- Reference: DETALLE_VENTA_VENTA (table: VENTA_DETALLE)
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT DETALLE_VENTA_VENTA FOREIGN KEY DETALLE_VENTA_VENTA (VENTA_CODVEN_VENVEN)
    REFERENCES VENTA (CODVEN);

-- Reference: DISTRITO_PROVINCIA (table: DISTRITO)
ALTER TABLE DISTRITO ADD CONSTRAINT DISTRITO_PROVINCIA FOREIGN KEY DISTRITO_PROVINCIA (PROVINCIA_CODPROV)
    REFERENCES PROVINCIA (CODPROV);

-- Reference: ENTRADASALIDA_PRODUCTO (table: ENTRADASALIDA)
ALTER TABLE ENTRADASALIDA ADD CONSTRAINT ENTRADASALIDA_PRODUCTO FOREIGN KEY ENTRADASALIDA_PRODUCTO (PRODUCTO_CODPRO)
    REFERENCES PRODUCTO (CODPRO);

-- Reference: MODELO_MARCA (table: MODELO)
ALTER TABLE MODELO ADD CONSTRAINT MODELO_MARCA FOREIGN KEY MODELO_MARCA (MARCA_CODMAR_MARMOD)
    REFERENCES MARCA (CODMAR);

-- Reference: PERSONA_DISTRITO (table: PERSONA)
ALTER TABLE PERSONA ADD CONSTRAINT PERSONA_DISTRITO FOREIGN KEY PERSONA_DISTRITO (DISTRITO_CODDIS_DISPER)
    REFERENCES DISTRITO (CODDIS);

-- Reference: PRODUCTO_MODELO (table: PRODUCTO)
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_MODELO FOREIGN KEY PRODUCTO_MODELO (MODELO_CODMOD_MODPRO)
    REFERENCES MODELO (CODMOD);

-- Reference: PRODUCTO_PERSONA (table: PRODUCTO)
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_PERSONA FOREIGN KEY PRODUCTO_PERSONA (PERSONA_CODPER_PROVPRO)
    REFERENCES PERSONA (CODPER);

-- Reference: PROVINCIA_DEPARTAMENTO (table: PROVINCIA)
ALTER TABLE PROVINCIA ADD CONSTRAINT PROVINCIA_DEPARTAMENTO FOREIGN KEY PROVINCIA_DEPARTAMENTO (DEPARTAMENTO_CODDEP)
    REFERENCES DEPARTAMENTO (CODDEP);

-- Reference: VENTA_PERSONA_CODPERCOMVE (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_PERSONA_CODPERCOMVE FOREIGN KEY VENTA_PERSONA_CODPERCOMVE (CODPER_COMVEN)
    REFERENCES PERSONA (CODPER);

-- Reference: VENTA_PERSONA_CODPERVENVE (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_PERSONA_CODPERVENVE FOREIGN KEY VENTA_PERSONA_CODPERVENVE (CODPER_VENVEN)
    REFERENCES PERSONA (CODPER);

-- End of file.

