USE iVentas;

CREATE FUNCTION AUTENTICAR(USER varchar(30), CONTRA varchar(10)) RETURNS CHAR(1)
BEGIN
    IF EXISTS (SELECT PERSONA.USRLOGPER FROM PERSONA WHERE (PERSONA.USRLOGPER = USER) AND (PERSONA.PSWLOGPER = CONTRA) AND (PERSONA.ESTLOGPER='A')) THEN
        RETURN (
            SELECT PERSONA.TIPPER 
            FROM PERSONA
            WHERE (PERSONA.USRLOGPER = USER) AND (PERSONA.PSWLOGPER = CONTRA)
        );
    ELSE
        RETURN '0';
    END IF;
END;
