USE SISTCOMP;

CREATE FUNCTION DEVCODLOG(DNI CHAR(8)) RETURNS INT
BEGIN
    RETURN (
        SELECT PERSONA.CODPER 
        FROM PERSONA 
        INNER JOIN LOGIN ON PERSONA.CODPER = LOGIN.PERSONA_CODPER 
        WHERE PERSONA.DNIPER = DNI
    );
END;

CREATE FUNCTION DEVCODPER(DNI CHAR(8)) RETURNS INT
BEGIN
    RETURN (
        SELECT PERSONA.CODPER 
        FROM PERSONA 
        WHERE PERSONA.DNIPER = DNI
    );
END;

CREATE FUNCTION DEVTIPPER(USER VARCHAR(30)) RETURNS CHAR(1)
BEGIN
    RETURN (
    SELECT PERSONA.TIPPER 
    FROM PERSONA
    INNER JOIN LOGIN ON PERSONA.CODPER = LOGIN.PERSONA_CODPER
    WHERE LOGIN.USRPER = USER);
END;

CREATE FUNCTION AUTENTICAR(USER varchar(30), CONTRA varchar(10)) RETURNS CHAR(1)
BEGIN
    DECLARE TIPO CHAR(1);
    IF EXISTS (SELECT * FROM LOGIN WHERE (USRPER = USER) AND (PSWPER = CONTRA)) THEN
        RETURN DEVTIPPER(USER);
    ELSE
        RETURN '0';
    END IF;
END;
