USE iVentas;


CREATE PROCEDURE ACCIONEMPRESA(
    IN _RUCEMP CHAR(10),
    IN _TLFEMP CHAR(12),
    IN _EMAILEMP VARCHAR(30),
    IN _DNIPER CHAR(8),
    IN TIPAC CHAR(2)
)
BEGIN
    CASE TIPAC
        WHEN 'RE' THEN
            IF NOT EXISTS (SELECT RUCEMP FROM EMPRESA WHERE RUCEMP = _RUCEMP) THEN
                INSERT INTO EMPRESA /*aumentara*/
                        (RUCEMP, TLFEMP, EMAILEMP, PERSONA_CODPER_REPLEG)
                    VALUES
                        (_RUCEMP, _TLFEMP, _EMAILEMP, DEVCODPER(_DNIPER));
            END IF;

    END CASE;
END;