USE SISTCOMP;

CREATE FUNCTION DEVCODLOG(DNI CHAR(8)) RETURNS INT
BEGIN
    RETURN (
        SELECT PERSONA.CODPER 
        FROM PERSONA 
        INNER JOIN LOGIN ON PERSONA.CODPER = LOGIN.PERSONA_CODPER 
        WHERE PERSONA.DNIPER = DNI
    );
END;

CREATE FUNCTION DEVCODMAR(_NOMMAR VARCHAR(50)) RETURNS INT
BEGIN
    RETURN(
        SELECT MARCA.CODMAR
        FROM MARCA
        WHERE MARCA.NOMMAR = _NOMMAR
    );
END;

CREATE FUNCTION DEVCODMOD(_NOMMOD VARCHAR(100)) RETURNS INT
BEGIN
    RETURN(
        SELECT MODELO.CODMOD
        FROM MODELO
        WHERE MODELO.NOMMOD = _NOMMOD
    );
END;

CREATE FUNCTION DEVCODPER(DNI CHAR(8)) RETURNS INT
BEGIN
    RETURN (
        SELECT PERSONA.CODPER 
        FROM PERSONA 
        WHERE PERSONA.DNIPER = DNI
    );
END;

CREATE FUNCTION DEVTIPPER(USER VARCHAR(30)) RETURNS CHAR(1)
BEGIN
    RETURN (
    SELECT PERSONA.TIPPER 
    FROM PERSONA
    INNER JOIN LOGIN ON PERSONA.CODPER = LOGIN.PERSONA_CODPER
    WHERE LOGIN.USRLOG = USER
    );
END;

CREATE FUNCTION AUTENTICAR(USER varchar(30), CONTRA varchar(10)) RETURNS CHAR(1)
BEGIN
    IF EXISTS (SELECT * FROM LOGIN WHERE (USRLOG = USER) AND (PSWLOG = CONTRA)) THEN
        RETURN DEVTIPPER(USER);
    ELSE
        RETURN '0';
    END IF;
END;
