USE iVentas;

INSERT INTO PERSONA 
(NOMPER, APEPER, DNIPER, TLFPER, TIPPER, DISTRITO_CODDIS_DISPER, DIRPER, USRLOGPER, PSWLOGPER, ESTLOGPER) 
VALUES ('MARTIN ALEXIS','SAMAN ARATA','72720455','+51974091056','A','15','Urb. Valle Hermoso MzD Lt21','admin','admin','A');

INSERT INTO MARCA (NOMMAR) VALUES ('HP');
INSERT INTO MODELO (NOMMOD, MARCA_CODMAR_MARMOD) VALUES ('modelo',2);

INSERT INTO EMPRESA (RUCEMP, TLFEMP, EMAILEMP, PERSONA_CODPER_REPLEG, TIPEMP, DISTRITO_CODDIS_DISEMP, DIREMP) VALUES
('12345678909','+99999999999','demo@example.com',8,'2',15,'urb.');

INSERT INTO PRODUCTO (NOMPRO, MODELO_CODMOD_MODPRO, SERPRO, PREPO, URLIMGPRO, ATRIBPRO, ESTPRO, FECGARPRO, EMPRESA_CODEMP_PROV) VALUES ('CELULAR',2,'seriee',20.2,'URLIMAGENCD','JSON','A',12-12-2018,1);




