USE SISTCOMP;

SELECT AUTENTICAR ('admin','admin');
SELECT DEVCODLOG('12121212');

SELECT * FROM PERSONA;
SELECT * FROM LOGIN;


SELECT * FROM LOGIN;
SELECT PERSONA.CODPER, PERSONA.NOMPER, PERSONA.APEPER, PERSONA.DNIPER, PERSONA.TLFPER, LOGIN.USRLOG, LOGIN.PSWLOG, LOGIN.ESTLOG, PERSONA.TIPPER FROM PERSONA INNER JOIN LOGIN ON PERSONA.CODPER = LOGIN.PERSONA_CODPER ;

